### PR TITLE
Reorganize and namespace modules

### PR DESCRIPTION
**Pull request by baldwindavid**
# What's changed?

- All modules moved under the `AddressUS` namespace
- Phone functions moved to a `Phone` module just because they didn't seem to belong in the parser
- Shared utils moved to a `Util` module and imported where needed

I would maybe consider exposing the public functions in the various modules at the top-level `AddressUS` module, but trying to avoid any changes outside moving modules around in this PR.

This was a super simple refactor, but no worries at all if this represents more moving pieces than you'd like.

### CODE REVIEW

**Comment by baldwindavid** [comment]
Also, don't read too much into the `bugfix/` namespacing. It created issues for my usage, but it's not really a library bug. :)

**Comment by smashedtoatoms** [comment]
This is killer.  I am so sorry it took so long to get this updated.  Thanks so much for doing this.  It's how it should have been done originally.

**Comment by baldwindavid** [comment]
Thanks for pulling in the changes. This is a reasonably big change for end-users. What do you think about cutting a new release and pushing to hex.pm? If not we can continue to follow our own fork until the next release. (As an aside, might also want to point the readme documentation to hex.).

**Comment by smashedtoatoms** [comment]
Ok, so I tried to release this as 0.5.0, but mix docs is throwing this when I try to release:

```
** (UndefinedFunctionError) function :string_lexer.string/1 is undefined (module :string_lexer is not available)
    (earmark_parser 1.4.12) :string_lexer.string(~c"Container for the struct that contains the Address information.")
    (earmark_parser 1.4.12) lib/earmark_parser/helpers/leex_helpers.ex:20: EarmarkParser.Helpers.LeexHelpers.tokenize/2
    (earmark_parser 1.4.12) lib/earmark_parser/helpers/lookahead_helpers.ex:17: EarmarkParser.Helpers.LookaheadHelpers.opens_inline_code/1
    (earmark_parser 1.4.12) lib/earmark_parser/parser.ex:531: EarmarkParser.Parser._inline_or_text?/2
    (earmark_parser 1.4.12) lib/earmark_parser/parser.ex:359: EarmarkParser.Parser._consolidate_para/3
    (earmark_parser 1.4.12) lib/earmark_parser/parser.ex:165: EarmarkParser.Parser._parse/4
    (earmark_parser 1.4.12) lib/earmark_parser/parser.ex:66: EarmarkParser.Parser.lines_to_blocks/3
    (earmark_parser 1.4.12) lib/earmark_parser/parser.ex:60: EarmarkParser.Parser.parse_lines/3
```

I started trying to update dependencies, and I just keep failing for all new and exciting reasons.  I haven't been using elixir as my daily professional driver since 1.6.  Is there any chance you can take a stab at getting this healthy?  If you all are actively using it, do you want to take it over?  It's totally fine if you don't want to do either, but I am not going to have time to chase my tail trying to figure out why what should be kind of a gimme built-in feature isn't working until maybe next weekend.

**Comment by baldwindavid** [comment]
Don't sweat it, @smashedtoatoms . Let me discuss with our team a bit about a path forward. I'm sure I can help out cutting a release regardless so don't worry about that. Have a good one.

**Comment by baldwindavid** [comment]
@smashedtoatoms Looks like you got the release figured out; sorry I went radio silent there. Our team is pretty comfortable with the release that is there now and not looking to take over the project at this time. You might consider adding to the readme that you're looking for an active maintainer and get a taker. Thanks!

**Comment by smashedtoatoms** [comment]
All good!  I was raging at the time, but was able to figure it out.  Thanks for getting back to me.

**Pull request merged**
