### PR TITLE
Fixed two issues with uppercased address input and ran formatter

### PR DESCRIPTION
**Pull request by tmepple**
Hi @smashedtoatoms thanks for the helpful library!

I've been testing on many address and fixed a couple of issues faced when feeding the parser already uppercased addresses.  

First was the city name would be returned in uppercase if provided that way which caused tests to fail.  Now it makes sure to always return the city in title case (with the exception of directionals which are uppercased).

Second, I was running into issues with addresses such as "1410 N LYNHURST DR".  The Regex `~r/U.S./` was matching and replacing this... so I updated it to require literal `.` in that case.

Also hope you don't mind but I ran the default Elixir formatter against the code.  If you don't like that I can prepare another PR reverting the formatter.

### CODE REVIEW

**Comment by smashedtoatoms** [comment]
Cool man.  If the tests pass, I am game.  I am at work.  I will take a look later this afternoon and pull it in.  I love the auto-formatting!

**Comment by tmepple** [comment]
Thanks!  Appreciate the fast feedback.  Also appreciate the great test coverage in the library otherwise it would be too scary to iterate on the many corner cases.

I'm finding some other changes I'd like to submit in the coming days.  There shouldn't be too much controversy in them as (I think) they comply with Pub. 28.  The one case I'd like to handle is with my lists there often is supplementary information included in the address.  An example is "708 S HEATON (STATE ROAD 35)".  I'd like to remove the extra info from the name (where it currently lands) and parse as `%Street{name: "Heaton", primary_number: "708", pre_direction: "S", supplementary_info: "State Road 35"}`.

If I could do it without breaking any existing tests would you be be cool with that?

**Comment by smashedtoatoms** [comment]
Yea, totally.  I didn't write this off of any published spec.  It was done purely experimentally as I acquired more data, so if you're writing to a spec, I think that is WAY better.

**Comment by tmepple** [comment]
Awesome thanks Jason...  it already follows most all of the "low hanging fruit" of pub 28 which is great so I am focusing on the next ~6 corner cases I found without breaking any existing tests.  Most of my addresses are in Indiana right now but I plan on addressing more corner cases (oddities with Wisconsin and Brooklyn NY-style addresses, etc) soon.

I just noticed I've been pushing in master for my fork instead of feature branches which adds to this PR... sorry about that!  I added a bunch of debug logging to maintain my sanity while developing that I was going to remove prior to it being ready to review/merge.  Since it's not ready for review I will close this PR now and continue my work in a feature branch and not bother you again until time for review.  Thanks again for the feedback as I continue work on it.

**Comment by smashedtoatoms** [comment]
No problem.  I look forward to it.

**Comment by smashedtoatoms** [comment]
Hey @tmepple, where did you get with the standardization?  You want a hand with it?

**Comment by tmepple** [comment]
Hi @smashedtoatoms, I've worked on my fork a lot over the past 6 weeks.  I found dozens of new corner cases standardizing several huge messy address lists.  I'm still processing new lists (from multiple states) on a daily basis but it's quickly getting closer to stability.  

All tests pass but I had to change 2 of your tests (I commented the reasons) for my purposes.  Due to that I'm not certain you want to take my massive PR?  If so then I want to do some clean up mostly of my comments and logging before re-submitting.  If you want to look at it and let me know if you are interested it's in the `corner-cases` branch in my fork.

**Comment by smashedtoatoms** [comment]
Hey @tmepple, did anything ever shape up that you wanted to drop in here?

**Comment by tmepple** [comment]
It's a rather huge PR.  It includes rather significant code restructuring... did you want to take a look at it in the `corner-cases` branch in my fork first?  If you like what you see then I will look at how hard it would be for me to merge the recent commits, rebase, and make a PR.

**Comment by smashedtoatoms** [comment]
Sounds great.  I will take a look this weekend.

**Comment by smashedtoatoms** [comment]
I lied; this weekend was a disaster.  I have a three-year-old, and she cares little about my wants and desires.  I will try to get to this later this week or next weekend.  Sorry about that.

**Comment by tmepple** [comment]
No worries at all and I completely understand!  Mine are 18 and 16 at this point so much more independent and not interfering with my work much anymore.  That said they are much more expensive now requiring cars, university, tons of food, etc etc etc.  So you have that to look forward to!  

If you look at the code and think it's a monstrosity then no worries at all.  I will say I spent significant time processing huge lists of mostly business (not residential) addresses from gov't databases dealing with MANY corner cases (and writing tests so you can see what weird stuff I was solving for) which might be useful to others.

**Pull request closed without merging**
